routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\WarnaController;
use App\Http\Controllers\Admin\ListprodukController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/dasboard/', [DashboardController::class, 'index'])->name('dashboard');

Route::resource('listproduk', ListprodukController::class);

Route::resource('kategori', KategoriController::class);

Route::resource('warna', WarnaController::class);

//Route::get('/admin/kategori/index', [KategoriController::class, 'index'])->name('kategori');
//Route::get('/admin/kategori/form', [KategoriController::class, 'create'])->name('form');
//Route::post('/admin/kategori/index', [KategoriController::class, 'store'])->name('formStore');
//Route::patch('/admin/kategori/index/{id}', [KategoriController::class, 'update'])->name('formUpdate');
//Route::delete('/admin/kategori/index/{id}', [KategoriController::class, 'destroy'])->name('formDelete');


//Route::get('/admin/warna/warna', [WarnaController::class, 'index'])->name('warna');
//Route::get('/admin/warna/form', [WarnaController::class, 'create'])->name('formWarna');

//Route::get('/admin/listproduk/listproduk', [ListprodukController::class, 'index'])->name('listproduk');
//Route::get('/admin/listproduk/form', [ListprodukController::class, 'create'])->name('formListproduk');

app/Http/Controllers/Admin/ListprodukController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Produk;
use Illuminate\Http\Request;

class ListprodukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data['listproduk'] = Produk::all();
        return view('admin.listproduk.listproduk', $data);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.listproduk.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        dd($request->all());
        $rule = [
            'nama_produk' => 'required',
            'deskripsi_produk' => 'required|string',
            'foto_produk' => 'required',
        ];

        $this->validate($request, $rule);
        $foto='kosong jpg';
        $request['foto_produk']=$foto;
        $input = $request->all();
        $status = Produk::create($input);
        if ($status){
            return redirect('listproduk')->with('success', 'Data berhasil ditambahkan');
        }else{
            return redirect('listproduk/create')->with('error', 'Data gagal ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $rule = [
            'nama_produk' => 'required',
            'keterangan' => 'required|string',
        ];

        $this->validate($request, $rule);
        $input = $request->all();
        $produk = produk::find($id);
        $status = $produk->update($input);
        if ($status){
            return redirect('/admin/listproduk/listproduk')->with('success', 'Data berhasil diubah');
        }else{
            return redirect('/admin/listproduk/form')->with('error', 'Data gagal diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $produk = Produk::find($id);
        $status = $produk->delete();
        if ($status){
            return redirect('/admin/listproduk/listproduk')->with('success', 'Data berhasil di delete');
        }else{
            return redirect('/admin/listproduk/form')->with('error', 'Data gagal di delete');
        }
    }
}

resources/views/admin/listproduk/form.blade.php
@extends('admin.layout.app')

@section('content')

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Form Produk</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Forms</a>
                                </li>
                                <li class="breadcrumb-item active"><a href="#">Form Layouts</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">

            <!-- Basic Vertical form layout section start -->
            <section id="basic-vertical-layouts">
                <div class="row">
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Vertical Form with Icons</h4>
                            </div>
                            <div class="card-body">
                                <form class="form form-vertical" method="POST" action="{{route('listproduk.store')}}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="email-id-icon">Nama Produk</label>
                                                <div class="input-group input-group-merge">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i data-feather="mail"></i></span>
                                                    </div>
                                                    <input type="text" id="email-id-icon" class="form-control" name="email-id-icon" placeholder="Nama Produk" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="password-icon">Keterangan</label>
                                                <div class="input-group input-group-merge">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i data-feather="lock"></i></span>
                                                    </div>
                                                    <input type="text" id="password-icon" class="form-control" name="contact-icon" placeholder="Keterangan" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-icon">Foto</label>
                                                <div class="input-group input-group-merge">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i data-feather="smartphone"></i></span>
                                                    </div>
                                                    <input type="file" id="contact-info-icon" class="form-control" name="contact-icon" placeholder="Foto" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                            <button type="reset" class="btn btn-outline-secondary">Reset</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Basic Vertical form layout section end -->
        </div>
    </div>
</div>
<!-- END: Content-->

@endsection

resources/views/admin/listproduk/listproduk.blade.php
@extends('admin.layout.app')

@section('content')

<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">List Produk</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Table Bootstrap
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('listproduk.create')}}" class="btn btn-primary"> Add Produk </a>
                            <h4 class="card-title">Table Basic</h4>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                Using the most basic table Leanne Grahamup, here’s how <code>.table</code>-based tables look in Bootstrap. You
                                can use any example of below table for your table and it can be use with any type of bootstrap tables.
                            </p>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nama Produk</th>
                                        <th>Keterangan</th>
                                        <th>Foto</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($listproduk as $row)
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{$row->nama_produk}}</td>
                                        <td>{{$row->deskripsi_produk}}</td>
                                        <td>{{$row->foto_produk}}</td>
                                        <td>
                                            <a href="{{route('listproduk.edit', $row->id)}}" class="btn btn-warning"> Edit </a>
                                            <a href="{{route('listproduk.destroy', $row->id)}}" class="btn btn-danger"> Delete </a>
                                        </td>

                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
            

        </div>
    </div>
</div>
<!-- END: Content-->



@endsection