routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\KategoriController;
use App\Http\Controllers\Admin\WarnaController;
use App\Http\Controllers\Admin\ListprodukController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/dasboard/', [DashboardController::class, 'index'])->name('dashboard');

Route::resource('listproduk', ListprodukController::class);

Route::resource('kategori', KategoriController::class);

Route::resource('warna', WarnaController::class);

//Route::get('/admin/kategori/index', [KategoriController::class, 'index'])->name('kategori');
//Route::get('/admin/kategori/form', [KategoriController::class, 'create'])->name('form');
//Route::post('/admin/kategori/index', [KategoriController::class, 'store'])->name('formStore');
//Route::patch('/admin/kategori/index/{id}', [KategoriController::class, 'update'])->name('formUpdate');
//Route::delete('/admin/kategori/index/{id}', [KategoriController::class, 'destroy'])->name('formDelete');


//Route::get('/admin/warna/warna', [WarnaController::class, 'index'])->name('warna');
//Route::get('/admin/warna/form', [WarnaController::class, 'create'])->name('formWarna');

//Route::get('/admin/listproduk/listproduk', [ListprodukController::class, 'index'])->name('listproduk');
//Route::get('/admin/listproduk/form', [ListprodukController::class, 'create'])->name('formListproduk');

app/Models/kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 't_kategori';
    protected $fillable = [
       'jenis', 'keterangan'
    ];

    public function produk(){
        return $this->hasMany(Produk::class, 'id_kategori' ,'id');
    }

}

app/Http/Controllers/Admin/KategoriController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Kategori;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['kategori'] = Kategori::all();
        return view('admin.kategori.index', $data);
        //$data_kategori['kategori'] = Kategori::orderBy('id', 'asc')->get();
        //return view('admin.kategori.index', $data_kategori);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kategori.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rule = [
            'jenis' => 'required',
            'keterangan' => 'required|string',
        ];

        $this->validate($request, $rule);
        $input = $request->all();
        $status = Kategori::create($input);
        if ($status){
            return redirect('kategori')->with('success', 'Data berhasil ditambahkan');
        }else{
            return redirect('kategori/create')->with('error', 'Data gagal ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $kategori = Kategori::find($id);
        $data['kategori'] = $kategori;
        return view('admin.kategori.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $rule = [
            'jenis' => 'required',
            'keterangan' => 'required|string',
        ];

        $this->validate($request, $rule);
        $input = $request->all();
        $kategori = Kategori::find($id);
        $kategori->jenis = $request->jenis;
        $kategori->keterangan = $request->keterangan;


        $status = $kategori->save();
        if ($status){
            return redirect('kategori')->with('success', 'Data berhasil diubah');
        }else{
            return redirect('kategori/form')->with('error', 'Data gagal diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $kategori = Kategori::find($id);
        $status = $kategori->delete();
        if ($status){
            return redirect('kategori')->with('success', 'Data berhasil di hapus');
        }
    }
}

resources/views/admin/kategori/form.blade.php
@extends('admin.layout.app')

@section('content')

<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Form</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Forms</a>
                                </li>
                                <li class="breadcrumb-item active"><a href="#">Form Layouts</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">

            <!-- Basic Vertical form layout section start -->
            <section id="basic-vertical-layouts">
                <div class="row">
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">{{@$kategori ? 'Ubah' : 'Tambah'}} Kategori</h4>
                            </div>
                            <div class="card-body">
                                @if ($errors->any())
                                    <div class="alert alert-danger" role="alert">
                                    <h4 class="alert-heading">Error!</h4>
                                    @foreach ($errors->all() as $error)
                                        <div class="alert-body">
                                            {{$error}}
                                        </div>
                                    @endforeach
                                    </div>
                                @endif
                                <form class="form form-vertical" method="POST" action="{{@$kategori ? route('kategori.update', $kategori->id) : route('kategori.store')}}" enctype="multipart/form-data">
                                    @csrf
                                    @if(@$kategori)
                                        {{method_field('patch')}}
                                    @endif
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="email-id-icon">Jenis</label>
                                                <div class="input-group input-group-merge">
                                                    <input type="text" id="jenis" class="form-control"
                                                       name="jenis" placeholder="Jenis"
                                                        value="{{old('jenis', @$kategori ? $kategori->jenis : '') }} "/>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="password-icon">Keterangan</label>
                                                <div class="input-group input-group-merge">
                                                    <textarea name="keterangan" id="keterangan" cols="30"
                                                    rows="10" class="form-control">{{old('keterangan', @$kategori ? $kategori->keterangan : '')}}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <button type="reset" class="btn btn-outline-secondary">Back</button>
                                            <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Basic Vertical form layout section end -->
        </div>
    </div>
</div>
<!-- END: Content-->

@endsection

resources/views/admin/kategori/index.blade.php
@extends('admin.layout.app')

@section('content')

<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Kategori</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Table Bootstrap
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('kategori.create')}}" class="btn btn-primary"> Add Produk </a>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">Table Basic</h4>
                            <p class="card-text">
                                Using the most basic table Leanne Grahamup, here’s how <code>.table</code>-based tables look in Bootstrap. You
                                can use any example of below table for your table and it can be use with any type of bootstrap tables.
                            </p>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Jenis</th>
                                        <th>Keterangan</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($kategori as $row)
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$row->jenis}}</td>
                                    <td>{{$row->keterangan}}</td>
                                    <td>
                                        <a href="{{route('kategori.edit', $row->id)}}" class="btn btn-warning"> Edit </a>
                                        <form action="{{route('kategori.destroy', $row->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger"> Delete </button>
                                        </form>
                                    </td>
                                </tbody>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
            
            

        </div>
    </div>
</div>
<!-- END: Content-->


@endsection